name: Cleanup Environment - Destory

on:
  workflow_dispatch:

jobs:
  deployCoreInfra:
    runs-on: ubuntu-latest
    environment: airs
    env:
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}      

    steps:
      - uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init

        run: |
          terraform init \
          -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
          -backend-config="container_name=$CONTAINER_NAME" \
          -backend-config="resource_group_name=$RESOURCE_GROUP" \
          -backend-config="access_key=$STORAGE_ACCOUNT_KEY"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy
        run: terraform destroy --auto-approve

